# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://iwantmyreal.name/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: iwantmyrealname
github_username:  sammyd
logo: "/assets/glasses.png"

# Build settings
markdown: kramdown
paginate: 5
language: 'en-uk'
theme: jasper-theme
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - README.md
  - Gemfile
  - Gemfile.lock
  - .travis.yml
  - Rakefile

# Website info
name: 'iwantmyrealname'
description: "so I can use google to index things I fixed and then promptly forgot about"

# Author's info
author: 'Sam Davies'
nickname: sammyd
location: 'UK/Thailand'
image: 'assets/sam_headshot_small.jpg'

short_url: 'iwantmyreal.name'
google_analytics: UA-34836648-1
disqus: iwantmyrealname
# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: 

# Permalinks
permalink: /:slug
